export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const EMAIL_CHECKING = 'EMAIL_CHECKING';

export const HANDLING_CART_ITEM = 'HANDLING_CART_ITEM';
export const HANDLING_CART_CACULATOR = 'HANDLE_CART_CACULATOR';
