/* --- AUTH SCREENS --- */
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';
export const SIGN_IN_MANY_SCREEN = 'SIGN_IN_MANY_SCREEN'
export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN';
export const FORGOT_PASSWORD = {
    FORGOT_PASSWORD_VALIDATE_EMAIL_SCREEN : 'FORGOT_PASSWORD_VALIDATE_EMAIL_SCREEN',
    FORGOT_PASSWORD_VALIDATE_CODE_SCREEN: 'FORGOT_PASSWORD_VALIDATE_CODE_SCREEN',
    FORGOT_PASSWORD_NEW_PASSWORD_SCREEN : 'FORGOT_PASSWORD_NEW_PASSWORD_SCREEN',
}
export const INTRODUCTION_SCREEN = 'INTRODUCTION_SCREEN';

/* --- MAIN SCREENS --- */
export const HOME_SCREEN = 'HOME_SCREEN';
export const SEARCHING_SCREEN = 'SEARCHING_SCREEN';

/* --- NAVIGATION DRAWER SCREEN --- */
export const PROFILE = {
    MAIN_PROFILE_SCREEN : 'MAIN_PROFILE_SCREEN',
    CHANGE_AVATAR_SCREEN: 'CHANGE_AVATAR_SCREEN',
    EDIT_PROFILE_SCREEN: 'EDIT_PROFILE_SCREEN',
    CHANGE_PASSWORD_SCREEN: 'CHANGE_PASSWORD_SCREEN',
    STORE_LOCATION_SCREEN: 'STORE_LOCATION_SCREEN',
    UPGRADE_APP_SCREEN: 'UPGRADE_APP_SCREEN',
    ORDERING_ADDRESS: 'ORDERING_ADDRESS'
}
export const NOTIFICATION = {
    MAIN_NOTIFICATION: 'MAIN_NOTIFICATION',
    DETAIL_NOTIFICATION: 'DETAIL_NOTIFICATION',
}

export const CATEGORY = {
    CATEGORIES_SCREEN: 'CATEGORIES_SCREEN',
    PRODUCT_DETAIL_SCREEN: 'PRODUCT_DETAIL_SCREEN',
}

export const CART = {
    CHECKING_SCREEN: 'CHECKING_SCREEN',
    FINISHED_ORDER_SCREEN: 'FINISHED_ORDER_SCREEN',
    ORDER_STATE_SCREEN: 'ORDER_STATE_SCREEN',
    PAYMENT_SCREEN: 'PAYMENT_SCREEN',
}

export const FAVORITE_SCREEN = 'FAVORITE_SCREEN';
export const ORDERING_HISTORY_SCREEN = 'ORDERING_HISTORY_SCREEN';
export const VOUCHER_SCREEN = 'VOUCHER_SCREEN';
export const ABOUT_ME_SCREEN = 'ABOUT_ME_SCREEN';
